steps:
  - name: gcr.io/cloud-builders/docker
    id: build-image
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
      - -f
      - infra/cloudrun/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    id: push-image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-cloud-run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --project
      - $PROJECT_ID
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}

substitutions:
  _REGION: asia-northeast1
  _REPO: pyxis-repo
  _IMAGE: pyxis-fw
  _TAG: latest
  _SERVICE: pyxis-fw

timeout: 1800s

options:
  logging: CLOUD_LOGGING_ONLY
